import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '/styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'
import { NextPage } from 'next'

const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {
  // const [products, setProducts] = useState<
  //   { id: string; properties: { id: string }[]}[]
  //   >([])
  const [products, setProducts] = useState<{ id: string; name:string }[]>([])
  // useEffect(() => {
  //   fetch('/api/get-items').then((res) => res.json())
  //   .then((data) => setProducts(data.items))
  // },[])
  useEffect(() => {
    fetch('/api/get-products')
    .then((res) => res.json())
    .then((data) => setProducts(data.items))
  },[])

  const inputRef = useRef<HTMLInputElement>(null)
  const handleClick = () => {
    if (inputRef.current == null || inputRef.current.value === '') {
      alert('name을 넣어주세요.')
      return
    }
    fetch(`api/add-item?name=${inputRef.current.value}`)
      .then((res) => res.json())
      .then((data) => alert(data.message))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
         Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

          <input ref={inputRef} type="text" placeholder="name" />
          <button onClick={handleClick}>Add Jacket</button>
           
        <div> 
          <p>Product List</p>
          {products && products.map((item) => (
            <div key={item.id}>{item.name}</div> 
          ))}
          {/* {products && 
           products.map((item) => (
            <div key={item.id}>
              {JSON.stringify(item)}
              {item.properties && 
              Object.entries(item.properties).map(([key, value]) => (
                <button 
                key = {key} 
                onClick={() => {
                  fetch(
                   `/api/get-detail?pageId=${item.id}&propertyId=${value.id}`   
                  ) 
                    .then(res => res.json())
                    .then(data => alert(JSON.stringify(data.detail)))
                }}
                >
                  {key}
                </button>
              ))}
            <br />
            <br />
            </div>
          ))} */}
        </div>
      </main>
      </div>
  ) 
}

export default Home
        